aws_region = "eu-west-1"
lambda_function_name = "CsvToParquetFunc"
bucket_domain_name = "datalake-bucket"
lambda_zip_file = "lambdaZipFiles/csv_parquet.zip"
lambda_zip_bucket = "csv-to-parquet-config-bucket"
handler = "golang"